### PR TITLE
Feathers Auth Update

### PR DESCRIPTION
**Pull request by flyboarder**
This PR attempts to update to the new feathers-authentication-client.

It also fixes #127 which is the reason for this PR.

Seems tests are passing however the build is failing anyway?

### CODE REVIEW

**Comment by flyboarder** [comment]
@ekryski @daffl this change is holding up ClojureScript integration for the new auth.

**Comment by daffl** [comment]
Thank you! I think the failing tests are because of Saucelabs being a pain, it should be fixed when merged. I'm going to restructure some of the other clients as well so this will land in a little bit for the Auk release.

**Comment by flyboarder** [comment]
@daffl is there any way we can get an interm release? It's needed for a presentation for ClojureRemote at the beginning of February.

**Comment by ekryski** [comment]
Should be pretty quick @flyboarder. We'll just need to check some of the docs and then generator. We're trying to wrap that stuff by end of the year.

**Comment by flyboarder** [comment]
@daffl @ekryski thanks guys, I'll leave you too it then!

**Comment by daffl** [comment]
Sorry it took so long. Released as `v2.0.0-pre.1` (under the `pre` npm tag).

**Pull request merged**
