### PR TITLE
Add TypeScript type definitions.

### PR DESCRIPTION
**Pull request by ninachaubal**
### Summary

This provides TypeScript type definitions for projects using feathers-client with Angular2. It provides typings for auth functions and services.

### Other Information

More about typings: https://github.com/typings/typings/blob/master/docs/faq.md

### CODE REVIEW

**Comment by ninachaubal** [comment]
I'm not sure what's up with the feathers-hooks related errors. I'm seeing the same issue on a branch without my changes.

**Comment by daffl** [comment]
Thank you! I updated master to only run with one Node version, if you rebase the tests should be passing again now.

**Comment by ninachaubal** [comment]
Rebased. The saucelabs error is still in there :( What are the quotas on this thing? Perhaps we can wait for the rate limits to reset?

**Comment by daffl** [comment]
Odd... I'll merge and we can see if it passes.

**Pull request merged**
