### PR TITLE
Added flatten params method to query string process to allow for nest…

### PR DESCRIPTION
**Pull request by tkornblit**
Small commit to allow for objects / nested queries for REST requests.

### CODE REVIEW

**Comment by daffl** [comment]
Thank you! It looks like the tests aren't passing. This is the same issue as #19 right?

For Feathers 2 we already added a fix for it in https://github.com/feathersjs/feathers-rest by changing `querystring` to the `qs` module. Do you think that might work here as well?

**Comment by tkornblit** [comment]
Hey David,

Thanks for the quick response.

Not familiar with the qs module, but if it handles nested objects then it should work! Otherwise a simple flattener will do it before passing the object to the query string function.

Let me know if you want me to write the tests to make it pass.

-Tom
--
Tom Kornblit
Writer & World Traveler
Peep my b <http://blog.tomkornblit.com/>log <http://blog.tomkornblit.com/> to keep up with my adventures

**Comment by daffl** [comment]
I think it does the same thing. Would you mind changing your PR (or opening a new one) to that similar to https://github.com/feathersjs/feathers-rest/blob/master/src/client/base.js#L1 and https://github.com/feathersjs/feathers-rest/blob/master/src/client/base.js#L20? We also changed the test at https://github.com/feathersjs/feathers-client/blob/master/test/base.js#L15 to

```js
it('.get and params passing', function(done) {
      var query = {
        some: 'thing',
        other: ['one', 'two'],
        nested: { a: { b: 'object' } }
      };

      service.get(0, query).then(todo => assert.deepEqual(todo, {
        id: 0,
        text: 'some todo',
        complete: false,
        query: query
      })).then(() => done()).catch(done);
    });
});
```

If that passes we can get a patch version out right away.

**Comment by tkornblit** [comment]
Hey David,

Awesome. I will put in the new request over the next day or two. Been heads down on my own project (https://flurry.zeek.ai <https://flurry.zeek.ai/>).

Quick question for you - How do you typically structure your services? All in the app.js file? I would like to modularize it in an elegant way (without injecting the app = feathers() object into service files). Basically it would be nice to be able to require the feathers module and access the services instead of injecting them.

Is there a way to do that?

-Tom
--
Tom Kornblit
Writer & World Traveler
Peep my b <http://blog.tomkornblit.com/>log <http://blog.tomkornblit.com/> to keep up with my adventures

**Comment by tkornblit** [comment]
Nvm got it. Nice!
--
Tom Kornblit
Writer & World Traveler
Peep my b <http://blog.tomkornblit.com/>log <http://blog.tomkornblit.com/> to keep up with my adventures

**Comment by daffl** [comment]
That looks interesting. We should start a "who is using Feathers" list :)

It is not completely done but way we usually structure our services and files can be found in the Yeoman generator at https://github.com/feathersjs/generator-feathers.

Updating the client to Feathers 2 (it should also still work with a v1 server) may also fix your problem by the way. If you have too much on your plate, I wanted to look into updating this module in the next few days. This is how it works now:

```js
var feathers = require('feathers/client');
var socketio = require('feathers-socketio/client');
var io = require('socket.io-client');

var socket = io();
var app = feathers().configure(socketio(socket));

var service = app.service('my/remote/service');
```

**Comment by ekryski** [comment]
I think we might have this fixed in the 1.0.0-pre release?

**Comment by daffl** [comment]
Yes, this is fixed now. Sorry @tkornblit for not getting this PR in, we really appreciate it and I hope the new client version works for you.

**Comment by tkornblit** [comment]
Hey David,

Just wanted to comment as I’m seeing this question on the internet of why Feathers over Meteor:

If you’re building a B2B/on-premise product, I would say Meteor is a good solution.

But for scale, Meteor sucks. Why? Because it’s entirely web sockets, and they lock you into it.

Feathers offers both web sockets and REST. Which is a huge advantage.

Also, if you’re someone who likes to plug and play. Feathers all the way.

Those should be the 2 main factors here on our page: http://docs.feathersjs.com/why/vs/meteor.html <http://docs.feathersjs.com/why/vs/meteor.html>

Thanks for creating such an awesome project.

-Tom
--
Tom Kornblit

**Comment by ekryski** [comment]
@tkornblit thanks for those comments. I completely agree. Would you want to put that into a PR? 😁 

Just click the "Edit this page" link at the top of the docs.

**Pull request closed without merging**
